// Code generated by "stringer -type=RSSFeed"; DO NOT EDIT.

package habr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FeedDaily-0]
	_ = x[FeedWeekly-1]
	_ = x[FeedMonthly-2]
	_ = x[FeedYearly-3]
	_ = x[FeedAllTime-4]
	_ = x[_feedCount-5]
}

const _RSSFeed_name = "FeedDailyFeedWeeklyFeedMonthlyFeedYearlyFeedAllTime_feedCount"

var _RSSFeed_index = [...]uint8{0, 9, 19, 30, 40, 51, 61}

func (i RSSFeed) String() string {
	if i < 0 || i >= RSSFeed(len(_RSSFeed_index)-1) {
		return "RSSFeed(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RSSFeed_name[_RSSFeed_index[i]:_RSSFeed_index[i+1]]
}
